<?php
/**
 * Created by PhpStorm.
 * User: sunxiaozhi
 * Date: 2018/9/18
 * Time: 21:59
 */

namespace frontend\components;

use yii\base\Component;

class Site extends Component
{
    public $siteInfo = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}