<?php
/**
 * 网站配置
 * Author: sunhuanzhi
 * Date: 2018/10/8 16:36
 */

namespace common\components;

use yii\base\Component;
use common\models\Config;

class SiteConfig extends Component
{
    public $configData;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->configData = Config::find()->where('')->all();
    }

    public function getSiteConfigs()
    {
    }
}