<?php
/**
 * Created by PhpStorm.
 * User: sunxiaozhi
 * Date: 2018/9/15
 * Time: 21:49
 */

namespace backend\models;

use Yii;
use common\models\Article as BaseArticle;
use common\models\ArticleTag;
use common\models\ArticleTagRelation;

class Article extends BaseArticle
{
    /**
     * 执行保存标签的操作
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $articele_id = $this->id;

        if (Yii::$app->request->isPost) {
            $formArticle = Yii::$app->request->post('Article');

            if (isset($formArticle['tag']) && !empty($formArticle['tag'])) {
                $tagArr = explode(',', $formArticle['tag']);

                //清除所有的文章和标签的关系
                $ArticleTagRelation = new ArticleTagRelation();
                $ArticleTagRelation::deleteAll(['article_id' => $articele_id]);

                //依次添加文章和标签的关系
                foreach ($tagArr as $key => $val) {
                    if (!empty($val)) {
                        $articeleTagData = ArticleTag::find()->where(['name' => $val])->one();

                        //标签不存在，则添加
                        if (empty($articeleTagData)) {
                            $articeleTag = new ArticleTag();
                            $articeleTag->name = $val;
                            $articeleTag->alias = $val;
                            $articeleTag->save();

                            $tag_id = $articeleTag->id;
                        } else {
                            $tag_id = $articeleTagData->id;
                        }
                    } else {
                        continue;
                    }

                    $ArticleTagRelation = new ArticleTagRelation();
                    $ArticleTagRelation->article_id = $articele_id;
                    $ArticleTagRelation->tag_id = $tag_id;
                    $ArticleTagRelation->save();
                }
            }
        }
    }
}