<?php
/**
 * Created by PhpStorm.
 * User: sunxiaozhi
 * Date: 2018/9/15
 * Time: 21:49
 */

namespace backend\models;

use common\models\Article as BaseArticle;

class Article extends BaseArticle
{
    /**
     * 执行保存标签的操作
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}