<?php
/**
 * 文章列表部件
 *
 * User: sunhuanzhi
 * Date: 2018/3/22
 * Time: 9:50
 */

namespace frontend\widgets;

use Yii;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\helpers\StringHelper;

class ArticleListView extends \yii\widgets\ListView
{
    public $layout = "{items}\n<div class=\"pagination pagination-centered\">{pager}</div>";
    public $pagerOptions = [
        'firstPageLabel' => '首页',
        'lastPageLabel' => '尾页',
        'prevPageLabel' => '上一页',
        'nextPageLabel' => '下一页',
        'options' => [
            'class' => '',
        ],
    ];

    public $template = "<div class='blog margin-bottom-30'>
        <h3>{title}</h3>
        <ul class='unstyled inline blog-info'>
            <li><i class='icon-calendar'></i> {pub_date}</li>
            <li><i class='icon-pencil'></i> Diana Anderson</li>
            <li><i class='icon-comments'></i> <a href='#'>24 Comments</a></li>
        </ul>
        <ul class='unstyled inline blog-tags'>
            <li>
                <i class='icon-tags'></i>
                <a href='#'>Technology</a>
                <a href='#'>Education</a>
                <a href='#'>Internet</a>
                <a href='#'>Media</a>
            </li>
        </ul>
        <div class='blog-img'><img src='basic_assets/img/posts/1.jpg' alt='' /></div>
        <p>{abstract}</p>
        <p><a class='btn-u btn-u-small' href='{article_url}'>Read More</a></p>
    </div>";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->itemView = function ($model, $key, $index) {
            //文章链接
            $url = Url::to(['site/index', 'id' => $model->id]);
            //分类名称
            //$categoryName = $model->category_id ? $model->category->id : Yii::t('app', 'uncategoried');
            //分类链接
            //$categoryUrl = Url::to(['article/index', 'cat' => $categoryName]);
            //创建时间
            $pubTime = Yii::$app->getFormatter()->asDatetime($model->created_at);
            //文章图片
            if (!empty($model->thumb)) {
                $imgUrl = "/timthumb.php?src=" . $model->thumb . "&h=112&w=168&zc=0";
            } else {
                $imgUrl = '/static/images/' . rand(1, 10) . '.jpg';
            }
            //文章链接
            $articleUrl = Url::to(['article/view', 'id' => $model->id]);
            //文章简介
            $abstract = StringHelper::truncate($model->abstract, 120);
            //文章标题
            $title = StringHelper::truncate($model->title, 28);
            //文章作者
            //$author_name = StringHelper::truncate($model->author_name, 28);
            //文章标签
            $article_tag = '';
            if (!empty($model->tag)) {
                $arr_article_tag = explode(',', $model->tag);
                foreach ($arr_article_tag as $v) {
                    $article_tag .= "<a href='" . Url::to(['search/index', 'q' => $v]) . "'>$v</a>&nbsp;&nbsp";
                }
            }

            return str_replace([
                '{article_url}',
                '{img_url}',
                //'{category_url}',
                '{title}',
                //'{author_name}',
                '{abstract}',
                '{pub_date}',
                //'{scan_count}',
                '{comment_count}',
                '{category}',
                '{comment_url}',
                '{article_tag}'
            ], [
                $articleUrl,
                $imgUrl,
                //$categoryUrl,
                $title,
                //$author_name,
                $abstract,
                date('Y-m-d', $model->created_at),
                //$model->scan_count,
                //$model->comment_count,
                //$categoryName,
                $articleUrl . "#comments",
                $article_tag
            ], $this->template);
        };
    }

    public function renderPager()
    {
        $pagination = $this->dataProvider->getPagination();
        if ($pagination === false || $this->dataProvider->getCount() <= 0) {
            return '';
        }

        /* @var $class LinkPager */
        $pager = $this->pager;
        $class = ArrayHelper::remove($pager, 'class', LinkPager::className());
        $pager['pagination'] = $pagination;
        $pager['view'] = $this->getView();
        $pager = array_merge($pager, $this->pagerOptions);
        return $class::widget($pager);
    }
}
