<?php
/**
 * WitCMS
 * 文章列表部件
 * Author: sunxiaozhi
 * Date: 2018/10/13 11:59
 */

namespace frontend\widgets;

use Yii;
use common\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\helpers\StringHelper;

class ArticleListView extends \yii\widgets\ListView
{
    public $layout = "{items}\n<div class=\"pagination pagination-centered\">{pager}</div>";
    public $pagerOptions = [
        'firstPageLabel' => '首页',
        'lastPageLabel' => '尾页',
        'prevPageLabel' => '上一页',
        'nextPageLabel' => '下一页',
        'options' => [
            'class' => '',
        ],
    ];

    public $template = "<div class='blog margin-bottom-30'>
        <h3>{title}</h3>
        <ul class='unstyled inline blog-info'>
            <li><i class='fa fa-calendar'></i> {pub_date}</li>
            <li><i class='fa fa-pencil'></i> Sun Xiaozhi</li>
            <li><i class='fa fa-eye'></i> {page_views}</li>
            <!--<li><i class='fa fa-comments'></i> <a href='#'>24 Comments</a></li>-->
        </ul>
        <ul class='unstyled inline blog-tags'>
            <li>
                <i class='fa fa-tags'></i>
                {article_tag}
            </li>
        </ul>
        <div class='blog-img'><img src='{article_thumb}' alt='' /></div>
        <p>{abstract}</p>
        <p style='float: right'><a class='btn-u btn-u-small' href='{article_url}'>阅读更多</a></p>
    </div>";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->itemView = function ($model, $key, $index) {
            //创建时间
            $pubTime = Yii::$app->getFormatter()->asDatetime($model->created_at);
            //文章图片
            if (!empty($model->thumb)) {
                $imgUrl = "/timthumb.php?src=" . $model->thumb . "&h=112&w=168&zc=0";
            } else {
                $imgUrl = '/static/images/' . rand(1, 10) . '.jpg';
            }
            //文章链接
            $articleUrl = Url::to(['article/view', 'id' => $model->id]);
            //文章简介
            $abstract = StringHelper::truncate($model->abstract, 120);
            //文章标题
            $title = StringHelper::truncate($model->title, 28);
            //文章浏览量
            $pageViews = $model->page_views;
            //文章作者
            //$author_name = StringHelper::truncate($model->author_name, 28);
            //文章图片
            $articleThumb = Url::toImage($model->thumb);
            //文章标签
            $article_tag = '';
            if (!empty($model->articleTag)) {
                foreach ($model->articleTag as $key => $val) {
                    $article_tag .= "<a href='" . Url::to(['article/index', 'tid' => $val->id]) . "'>$val->name</a>";
                }
            }

            return str_replace([
                '{article_url}',
                '{article_thumb}',
                '{title}',
                '{abstract}',
                '{pub_date}',
                '{page_views}',
                '{article_tag}'
            ], [
                $articleUrl,
                $articleThumb,
                $title,
                $abstract,
                $pubTime,
                $pageViews,
                $article_tag
            ], $this->template);
        };
    }

    public function renderPager()
    {
        $pagination = $this->dataProvider->getPagination();
        if ($pagination === false || $this->dataProvider->getCount() <= 0) {
            return '';
        }

        /* @var $class LinkPager */
        $pager = $this->pager;
        $class = ArrayHelper::remove($pager, 'class', LinkPager::className());
        $pager['pagination'] = $pagination;
        $pager['view'] = $this->getView();
        $pager = array_merge($pager, $this->pagerOptions);
        return $class::widget($pager);
    }
}
