<?php
/**
 * WitCMS
 * 面包屑导航
 * Author: sunhuanzhi
 * Date: 2018/9/20 11:05
 */

namespace frontend\widgets;

use yii\base\Widget;

class Breadcrumbs extends Widget
{
    public $breadcrumbTitle;
    public $breadcrumbItem;

    public $template = '<div class="breadcrumbs margin-bottom-10">
                            <div class="container">
                                <h1 class="color-green pull-left">{breadcrumbTitle}{breadcrumbItem}</h1>
                            </div>
                        </div>';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $breadcrumbTitle = !empty($this->breadcrumbTitle) ? $this->breadcrumbTitle : \Yii::t('frontend', 'Latest Posts');
        $breadcrumbItem = '<span>' . (!empty($this->breadcrumbItem) ? $this->breadcrumbItem : '') . '</span>';

        return str_replace([
            '{breadcrumbTitle}',
            '{breadcrumbItem}'
        ], [
            $breadcrumbTitle,
            $breadcrumbItem
        ], $this->template);

    }
}